### PR TITLE
Hotfix/resolve conflit

### PR DESCRIPTION
**Pull request by azizalshrafi**

### CODE REVIEW

**Review by mohammedalian — COMMENTED** [review]
resolve conflicts

**Comment by fahjan** [comment]
resolve conflicts please

**Comment by AbdalazizAbdallah** [comment]
Please edit your pull request to resolve your conflict..
Search how to edit merge in pull request .. or in front of Name pull request you see Edit Button use it

**Review by AbdalazizAbdallah — CHANGES_REQUESTED** [review]
See last comment

**Comment by azizalshrafi** [comment]
> See last comment  

Oky I will try fix pull request

**Pull request closed without merging**
